export V?=0

include config.mk

# If _HOST or _TA specific compilers are not specified, then use CROSS_COMPILE
HOST_CROSS_COMPILE ?= $(CROSS_COMPILE)
TA_CROSS_COMPILE ?= $(CROSS_COMPILE)

.PHONY: all
all:
	echo "$(HOST_CROSS_COMPILE)"
	echo "$(TA_CROSS_COMPILE)"
	$(MAKE) -C host CROSS_COMPILE="$(HOST_CROSS_COMPILE)" TEEC_EXPORT="$(TEEC_EXPORT)" TA_DEV_KIT_DIR="$(TA_DEV_KIT_DIR)"
	$(MAKE) -C ta CROSS_COMPILE="$(TA_CROSS_COMPILE)" TEEC_EXPORT="$(TEEC_EXPORT)" TA_DEV_KIT_DIR="$(TA_DEV_KIT_DIR)"

.PHONY: clean
clean:
	$(MAKE) -C host clean CROSS_COMPILE="$(TA_CROSS_COMPILE)" TEEC_EXPORT="$(TEEC_EXPORT)" TA_DEV_KIT_DIR="$(TA_DEV_KIT_DIR)"
	$(MAKE) -C ta clean CROSS_COMPILE="$(TA_CROSS_COMPILE)" TEEC_EXPORT="$(TEEC_EXPORT)" TA_DEV_KIT_DIR="$(TA_DEV_KIT_DIR)"
